### ISSUE TITLE
About Dataset Download

### ISSUE THREAD

**Issue by zzxmllq** [felix-ch/f3loc#1]
hi~Thank you for your excellent work and for open-sourcing the code. I am interested in downloading the dataset you provided in your code for some experiments, but it is stored on libdrive, and I encounter an error when accessing the webpage. Could you please upload the data to another platform, such as Baidu Netdisk? I would greatly appreciate it.

**Comment by felix-ch** [comment]
Hi, thank you for your interest! Can you tell me what kind of error you encountered?

**Comment by zzxmllq** [comment]
Thanks for your reply, I have resolved the issue~

**Comment by GauleeJX** [comment]
Hello, thanks for your excellent work! However, I also encounter the same problem downloading the dataset. I have two problems:
1. I had access to libdrive last night, but when I clicked the download button it took too much time to zip the data for downloading and the download was interrupted midway. 
2. So I have to download it again, but this morning I cannot have access to libdrive normally when I can have access ti google normally.
Thanks for your excellent work and open-sourcing code again. Is there another way to download this dataset, like GoogleDrive or others?
