### ISSUE TITLE
Download dataset

### ISSUE THREAD

**Issue by GauleeJX** [felix-ch/f3loc#2]
Hello, thanks for your excellent work! However, I also encounter the same problem downloading the dataset. I have two problems:
1. I had access to libdrive last night, but when I clicked the download button it took too much time to zip the data for downloading and the download was interrupted midway. And I have tried many times, but it always lost the connection. 
2. So I have to download it again, but this morning I cannot have access to libdrive normally when I can have access to google normally.
Is there another way to download this dataset, like GoogleDrive or others? Or could you update the data in another netdisk？
Thanks for your excellent work and open-sourcing code again！

**Comment by felix-ch** [comment]
Hi, sorry that the libdrive is the only way we can distribute the dataset. If losing connection frequently is a problem, I would suggest finding a place where has stable internet connection and using a download manager such as https://www.downthemall.net/

**Comment by GauleeJX** [comment]
OK! Thanks a lot! I have downloaded them at another time.
